### ISSUE TITLE
Centroid improvement function on biscection

### ISSUE THREAD

**Issue by bobhancock** [bobhancock/goxmeans#12]
Page 3 of Pelleg-Moore: ...splitting each centroid into two children.  The are moved a distance proportional to the size of the region in opposite directions along a randomly chosen vector.

**Comment by danielhfrank** [comment]
@bobhancock - you could use my EllipseCentroidChooser with k=2 to accomplish this. You'd just need to decide how far apart you want them

**Comment by bobhancock** [comment]
I was thinking of that as I was writing it and was about to send a follow
up email asking about the suitability.  You are quick, thanks.

On Mon, Aug 6, 2012 at 1:11 PM, Dan Frank <
reply@reply.github.com

> wrote:
> 
> @bobhancock - you could use my EllipseCentroidChooser with k=2 to
> accomplish this. You'd just need to decide how far apart you want them
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bobhancock/goxmeans/issues/12#issuecomment-7529331

## 

Bob Hancock

Blog - www.bobhancock.org
Twitter - bob_hancock
https://profiles.google.com/hancock.robert/about

**Comment by danielhfrank** [comment]
No problem, just had to make sure you didn't waste any time re-implementing!
